spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/filesdb

application:
  inbound:
    path: ${PWD}/shared-integration-files

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
